// books/data.ts
export const booksData = [
  {
    id: 1,
    title: "Understanding Physics - Volume 1",
    subject: "Physics",
    grade: "Grade 10",
    language: "English",
    date: "12.15.2025",
    status: "Published",
  },
  {
    id: 2,
    title: "Modern Chemistry",
    subject: "Chemistry",
    grade: "Grade 12",
    language: "English",
    date: "12.12.2025",
    status: "Published",
  },
  {
    id: 3,
    title: "Basic Mathematics",
    subject: "Maths",
    grade: "Grade 6",
    language: "Sinhala",
    date: "12.10.2025",
    status: "Draft",
  },
  {
    id: 4,
    title: "Basic Mathematics",
    subject: "Maths",
    grade: "Grade 6",
    language: "Sinhala",
    date: "12.10.2025",
    status: "Draft",
  },
  {
    id: 5,
    title: "Basic Mathematics",
    subject: "Maths",
    grade: "Grade 6",
    language: "Sinhala",
    date: "12.10.2025",
    status: "Draft",
  },
  {
    id: 6,
    title: "Modern Chemistry",
    subject: "Chemistry",
    grade: "Grade 12",
    language: "English",
    date: "12.12.2025",
    status: "Published",
  },
  {
    id: 7,
    title: "Modern Chemistry",
    subject: "Chemistry",
    grade: "Grade 12",
    language: "English",
    date: "12.12.2025",
    status: "Published",
  },
  {
  id: 8,
    title: "Understanding Physics - Volume 1",
    subject: "Physics",
    grade: "Grade 10",
    language: "English",
    date: "12.15.2025",
    status: "Published",
  },
  {
  id: 9,
    title: "Understanding Physics - Volume 1",
    subject: "Physics",
    grade: "Grade 10",
    language: "English",
    date: "12.15.2025",
    status: "Published",
  },
  {id: 10,
    title: "Understanding Physics - Volume 1",
    subject: "Physics",
    grade: "Grade 10",
    language: "English",
    date: "12.15.2025",
    status: "Published",
  },
];
